version: '3.4'

services:
  api:
    build: api
    volumes: 
      - ./api:/go/src/app
    ports:
      - 3000
    stdin_open: true
  front:
    build: front
    volumes:
      - /usr/src/app/node_modules
      - ./front:/usr/src/app
    ports:
      - 3000
    stdin_open: true